name: Build and Release
on:
  push:
    tags:
      - 'v*' # Se déclenche sur v1.0, v2.1.3, etc.

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Build Binaries
        run: |
          # Compilation pour différentes architectures
          # Le nom du binaire doit correspondre à ton index.json
          GOOS=linux GOARCH=amd64 go build -o dist/dummy-driver-linux-amd64
          GOOS=windows GOARCH=amd64 go build -o dist/dummy-driver-windows-amd64.exe
          GOOS=darwin GOARCH=arm64 go build -o dist/dummy-driver-darwin-arm64

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/dummy-driver-linux-amd64
            dist/dummy-driver-windows-amd64.exe
            dist/dummy-driver-darwin-arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}